### ISSUE TITLE
pytorch和torch

### ISSUE THREAD

**Issue by Wublubdub** [cryer/AlphaZero_Quoridor#1]
测试环境中写的是pytorch，而代码中是torch，请问这两个库互相兼容吗？还有就是torch在win10 pycharm 的环境下能不能安装？torch是否必须在Linux下才能运行？

**Comment by cryer** [comment]
@Wublubdub 你好,就是用的pytorch,pytorch这个名字的意思是torch框架的python扩展,因为torch框架是没有python接口的,只能用lua语言编写.所以pytorch框架代码中为了保证一致性,都是写成torch的.pytorch和torch完全可以看成不同的框架,没啥联系,就是语法是类似的.torch框架用的人很少,因为lua语言是小众语言,一般只有搞游戏的才学这个语言.

pytorch框架0.4.0版本以后都是支持windows的,现在已经1.1.0版本了.

**Comment by Wublubdub** [comment]
明白了，感谢你的解答
